<?php
use yii\db\Migration;
use yii\db\Schema;

class m161019_050133_setting extends Migration {

	public function safeUp() {
		$tableOptions = 'CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE=InnoDB';
		$this->createTable('{{%setting}}', [
			'id'          => Schema::TYPE_PK . '',
			'parent_id'   => Schema::TYPE_INTEGER . '(11) NOT NULL DEFAULT "0"',
			'code'        => Schema::TYPE_STRING . '(32) NOT NULL',
			'name'        => Schema::TYPE_STRING . '(255)',
			'desc'        => Schema::TYPE_TEXT . '',
			'type'        => Schema::TYPE_STRING . '(255) NOT NULL',
			'store_range' => Schema::TYPE_STRING . '(255)',
			'store_dir'   => Schema::TYPE_STRING . '(255)',
			'value'       => Schema::TYPE_TEXT . '',
			'sort_order'  => Schema::TYPE_INTEGER . '(11) DEFAULT "50"',
			'store_url'   => Schema::TYPE_STRING . '(255)',
			'icon'        => Schema::TYPE_STRING . '(255) NOT NULL DEFAULT ""',
		], $tableOptions);
		$this->createIndex('parent_id', '{{%setting}}', 'parent_id', 0);
		$this->createIndex('code', '{{%setting}}', 'code', 0);
		$this->createIndex('sort_order', '{{%setting}}', 'sort_order', 0);
		$this->insert('{{%setting}}', [
			'id'          => '19',
			'parent_id'   => '39',
			'code'        => 'general_group',
			'name'        => 'General tab',
			'desc'        => '',
			'type'        => 'group',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '1',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '21',
			'parent_id'   => '19',
			'code'        => 'general_hotline',
			'name'        => 'general_hotline',
			'desc'        => 'general_hotline',
			'type'        => 'text',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '01234567890',
			'sort_order'  => '1',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '30',
			'parent_id'   => '39',
			'code'        => 'SEO',
			'name'        => 'SEO Tab',
			'desc'        => '',
			'type'        => 'group',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '2',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '31',
			'parent_id'   => '30',
			'code'        => 'seo_title',
			'name'        => 'seo_title',
			'desc'        => 'seo_title',
			'type'        => 'textarea',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => 'seo',
			'sort_order'  => '1',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '32',
			'parent_id'   => '30',
			'code'        => 'seo_description',
			'name'        => 'seo_description',
			'desc'        => 'seo_description',
			'type'        => 'textarea',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => 'seo_description',
			'sort_order'  => '2',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '39',
			'parent_id'   => '0',
			'code'        => 'general',
			'name'        => 'General',
			'desc'        => 'General',
			'type'        => 'action',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '1',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '40',
			'parent_id'   => '19',
			'code'        => 'general_language',
			'name'        => 'general_language',
			'desc'        => 'general_language',
			'type'        => 'select',
			'store_range' => 'en,vi',
			'store_dir'   => '',
			'value'       => 'en',
			'sort_order'  => '2',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '41',
			'parent_id'   => '0',
			'code'        => 'email',
			'name'        => 'Email',
			'desc'        => 'setting information email',
			'type'        => 'action',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => 'email',
			'sort_order'  => '1',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '42',
			'parent_id'   => '47',
			'code'        => 'smtp_port',
			'name'        => 'SMTP port',
			'desc'        => '',
			'type'        => 'text',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '3',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '43',
			'parent_id'   => '47',
			'code'        => 'smtp_host',
			'name'        => 'SMTP Host',
			'desc'        => '',
			'type'        => 'text',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '2',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '44',
			'parent_id'   => '47',
			'code'        => 'smtp_user',
			'name'        => 'SMTP User',
			'desc'        => '',
			'type'        => 'text',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '4',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '45',
			'parent_id'   => '47',
			'code'        => 'smtp_password',
			'name'        => 'SMTP Password',
			'desc'        => '',
			'type'        => 'password',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '5',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '46',
			'parent_id'   => '47',
			'code'        => 'from_email',
			'name'        => 'From Email',
			'desc'        => '',
			'type'        => 'email',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '1',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '47',
			'parent_id'   => '41',
			'code'        => 'email_group',
			'name'        => 'Email Setting Tab',
			'desc'        => '',
			'type'        => 'group',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => 'email setting tab',
			'sort_order'  => '1',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '48',
			'parent_id'   => '47',
			'code'        => 'email_encryption',
			'name'        => 'Email Encryption',
			'desc'        => '',
			'type'        => 'select',
			'store_range' => 'None,SSL,TLS',
			'store_dir'   => '',
			'value'       => 'SSL',
			'sort_order'  => '6',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '49',
			'parent_id'   => '39',
			'code'        => 'maintainance',
			'name'        => 'Maintainance',
			'desc'        => '',
			'type'        => 'group',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '1',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '50',
			'parent_id'   => '49',
			'code'        => 'web_active',
			'name'        => 'web_active',
			'desc'        => '',
			'type'        => 'switch',
			'store_range' => 'Deactive,Active',
			'store_dir'   => '',
			'value'       => 'Deactive',
			'sort_order'  => '1',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '51',
			'parent_id'   => '49',
			'code'        => 'web_active_content',
			'name'        => 'web_active_content',
			'desc'        => '',
			'type'        => 'roxymce',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => 'test',
			'sort_order'  => '1',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '52',
			'parent_id'   => '19',
			'code'        => 'general_logo',
			'name'        => 'general_logo',
			'desc'        => '',
			'type'        => 'file_url',
			'store_range' => '',
			'store_dir'   => '@backend/web/uploads/settings',
			'value'       => 'nava-tech.png',
			'sort_order'  => '1',
			'store_url'   => 'http://cms.nava.tech/backend/uploads/settings',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '53',
			'parent_id'   => '19',
			'code'        => 'general_favicon',
			'name'        => 'general_favicon',
			'desc'        => 'general_favicon',
			'type'        => 'file_url',
			'store_range' => '',
			'store_dir'   => '@backend/web/uploads/settings',
			'value'       => '',
			'sort_order'  => '1',
			'store_url'   => 'http://cms.nava.tech/backend/uploads/settings',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '54',
			'parent_id'   => '39',
			'code'        => 'group_backup',
			'name'        => 'Backup',
			'desc'        => '',
			'type'        => 'group',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '4',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '55',
			'parent_id'   => '54',
			'code'        => 'backup_email',
			'name'        => 'Email backup',
			'desc'        => '',
			'type'        => 'switch',
			'store_range' => 'No,Yes',
			'store_dir'   => '',
			'value'       => 'Yes',
			'sort_order'  => '1',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '56',
			'parent_id'   => '54',
			'code'        => 'backup_from_email',
			'name'        => 'Sent backup from email',
			'desc'        => '',
			'type'        => 'email',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => 'backup@mail.com',
			'sort_order'  => '2',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '57',
			'parent_id'   => '54',
			'code'        => 'backup_to_email',
			'name'        => 'Send backup to email',
			'desc'        => '',
			'type'        => 'email',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => 'support@mail.com',
			'sort_order'  => '3',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '58',
			'parent_id'   => '54',
			'code'        => 'backup_ftp',
			'name'        => 'FTP Backup',
			'desc'        => '',
			'type'        => 'switch',
			'store_range' => 'No,Yes',
			'store_dir'   => '',
			'value'       => 'No',
			'sort_order'  => '5',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '59',
			'parent_id'   => '54',
			'code'        => 'backup_ftp_host',
			'name'        => 'FTP Host',
			'desc'        => '',
			'type'        => 'text',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '6',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '60',
			'parent_id'   => '54',
			'code'        => 'backup_ftp_port',
			'name'        => 'FTP Port',
			'desc'        => '',
			'type'        => 'number',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '21',
			'sort_order'  => '7',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '61',
			'parent_id'   => '54',
			'code'        => 'backup_ftp_user',
			'name'        => 'FTP User',
			'desc'        => '',
			'type'        => 'text',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '8',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '62',
			'parent_id'   => '54',
			'code'        => 'backup_ftp_pass',
			'name'        => 'FTP Pass',
			'desc'        => '',
			'type'        => 'password',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '9',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '63',
			'parent_id'   => '54',
			'code'        => 'backup_ftp_ssl',
			'name'        => 'FTP SSL',
			'desc'        => '',
			'type'        => 'switch',
			'store_range' => 'False,True',
			'store_dir'   => '',
			'value'       => 'False',
			'sort_order'  => '10',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '64',
			'parent_id'   => '54',
			'code'        => 'backup_ftp_dir',
			'name'        => 'FTP Directory',
			'desc'        => '',
			'type'        => 'text',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '11',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '65',
			'parent_id'   => '54',
			'code'        => 'backup_ftp_timeout',
			'name'        => 'FTP Timeout',
			'desc'        => '',
			'type'        => 'number',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '90',
			'sort_order'  => '12',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '66',
			'parent_id'   => '54',
			'code'        => 'backup_ftp_append_time',
			'name'        => 'Append time to backed up file',
			'desc'        => '',
			'type'        => 'switch',
			'store_range' => 'False,True',
			'store_dir'   => '',
			'value'       => 'True',
			'sort_order'  => '13',
			'store_url'   => '',
			'icon'        => '',
		]);
		$this->insert('{{%setting}}', [
			'id'          => '67',
			'parent_id'   => '54',
			'code'        => 'backup_hr1',
			'name'        => 'backup_hr1',
			'desc'        => '',
			'type'        => 'separator',
			'store_range' => '',
			'store_dir'   => '',
			'value'       => '',
			'sort_order'  => '4',
			'store_url'   => '',
			'icon'        => '',
		]);
	}

	public function safeDown() {
		$this->dropIndex('parent_id', '{{%setting}}');
		$this->dropIndex('code', '{{%setting}}');
		$this->dropIndex('sort_order', '{{%setting}}');
		$this->dropTable('{{%setting}}');
	}
}
