<?php
namespace common\models;

use yii\helpers\ArrayHelper;

/**
 * @property string $shipping_address;
 * @property string $payment         ;
 * @property string $transport_mode  ;
 * @property string $p               ;
 *
 */
class User extends \navatech\role\models\User {


	public function rules() {
		$old = parent::rules(); // TODO: Change the autogenerated stub
		$new = [
			[
				[
					'password',
					'username',
				],
				'required',
				'on' => 'check',
			],
			[
				['confirmed_at','password'],
				'safe',
			],
			[
				[
					'username',
					'email',
				],
				'unique',
			],
		];
		return ArrayHelper::merge($old, $new);
	}

	public function getAllRole($id = null) {
		if ($id == null) {
			$role = Role::find()->where('id != 2')->andWhere('id!=3')->all();
			$name = ArrayHelper::map($role, 'id', 'name');
			return $name;
		} else {
			$name = Role::find()->andWhere(['id' => $id])->one();
			return $name;
		}
	}

	public function attributeLabels() {
		return [
			'id'       => ' ID',
			'username' => 'user',
			'email'    => 'email',
			'role_id'  => 'role',
		];
	}

	public function afterFind() {
	}
}
